### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zushenyan** [zushenyan/Workstation#1]
# Phase 1
- [x] add `normalize.css`.
- [x] add `strip-loader` for `console.log...`. (used `drop_console` in UglifyJS instead)
- [x] replace localhost with IP so that everyone can access dev server.
- [x] establish a `config` file for easy adjustment and refactor webpack configs.
- [x] establish a `json-server` for API testing.
- [x] test code splitting for better optimization. (https://webpack.js.org/guides/code-splitting/)
- [x] test calling API from `server.development.js`.
- [x] test importing images in `scss` file.
- [x] upgrade all packages.
- [x] `react-router` seems having some issues when upgrading to `3.0`...

# Phase 2
- [x] create a branch `basic`.
- [x] create a branch `redux` from `basic`.
