### ISSUE TITLE
todo 2

### ISSUE THREAD

**Issue by zushenyan** [zushenyan/Workstation#2]
# Bug
- [x] https://github.com/reactjs/react-router-redux/issues/179

# Todo
- [x] refactor webpack configs and folder structure.
- [x] remove `redux-immutable`.
- [ ] pin the version of `extract-text-webpack-plugin`.
- [x] upgrade to webpack 2.
- [x] support progressive web application. (https://github.com/NekR/offline-plugin)
- [x] support audio as assets.
- [x] better image compression loader. (https://github.com/tcoopman/image-webpack-loader)
- [x] pin the version of webpack 2 when it's finally released.
